project:
  type: website
  output-dir: docs

website:
  title: "Maronga's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cmaronga/codecraft.blog
      - icon: twitter
        href: https://twitter.com/krissianyo
format:
  html:
    theme: cosmo
    css: styles.css



