project:
  type: website
  output-dir: docs

website:
  title: "Christopher Maronga"
  site-url: https://cmaronga.github.io/codecraft.blog/
  description: "Christopher Maronga blog"
  comments: 
    utterances: 
      repo: cmaronga/codecraft.blog
  navbar:
    right:
      - text: "About"
        file: about.qmd
      - text: "Talks"
        file: talks/talks.qmd
      - text: "Publications"
        file: publications/publications.qmd
      - text: "CV"
        file: documents/Christopher_Maronga_Resume.pdf
      - icon: github
        href: https://github.com/cmaronga/codecraft.blog
      - icon: twitter
        href: https://twitter.com/krissianyo
      - icon: rss
        href: index.xml
format:
  html:
    theme: Flatly #(Materia # Simplex # Zephyr #litera)  ## These are my all favourite themes
    css: styles.css
    toc: true
    toc-depth: 4
    toc-location: left