project:
  type: website
  output-dir: docs

website:
  title: "Maronga's codecraft"
  site-url: https://cmaronga.github.io/codecraft.blog/
  description: "Christopher Maronga blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cmaronga/codecraft.blog
      - icon: twitter
        href: https://twitter.com/krissianyo
      - icon: rss
        href: index.xml
format:
  html:
    theme: Flatly #Materia # Simplex # Zephyr #litera  ## These are my all favourite themes
    css: styles.css
    toc: true
    toc-location: left
    comments: 
      utterances: 
        repo: cmaronga/codecraft.blog
        label: blogcomment
