---
#title: "&nbsp;"
toc: false
listing:
  - id: "publications"
    sort-ui: false
    #filter-ui: true
    categories: false
    #type: table
    page-size: 10
    #fields: [title, description]
    contents: 
      - "*.qmd"
resources:
  - "**"
  - "!(.qmd|.rmd)"
execute: 
  warning: false
  echo: false
---


## Contributed publications


```{r}
# load packages
pacman::p_load(dplyr,    
               reactable)

publications <- tibble::tribble(
  ~Publication, ~url, ~Year, ~ `Affiliated institution`,
  
  "Expected Benefits and Budget Impact From a Microsimulation Model Support the Prioritization and Implementation of Fracture Liaison Services", "https://asbmr.onlinelibrary.wiley.com/doi/full/10.1002/jbmr.4775?af=R", "2023", "University of Oxford",
  
  "Primary care consultations and pain medicine prescriptions: a comparison between patients with and without chronic pain after total knee replacemen", "https://bmcmusculoskeletdisord.biomedcentral.com/articles/10.1186/s12891-022-05492-6", "2022", "University of Oxford",
  
  "Characterising paediatric mortality during and after acute illness in Sub-Saharan Africa and South Asia: a secondary analysis of the CHAIN cohort using a machine learning approach", "https://www.thelancet.com/journals/eclinm/article/PIIS2589-5370(23)00015-9/fulltext#secsectitle0010", "2023", "KEMRI-Wellcome KEMRI-Wellcome Trust Research Programme",
  
 "Childhood mortality during and after acute illness in Africa and south Asia: a prospective cohort study", "https://www.sciencedirect.com/science/article/pii/S2214109X22001188#!", "2022", "KEMRI-Wellcome KEMRI-Wellcome Trust Research Programme",
 
 "A systematic review of the quality of conduct and reporting of survival analyses of tuberculosis outcomes in Africa", "https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-021-01280-3", "2021", "KEMRI-Wellcome KEMRI-Wellcome Trust Research Programme",
 
"The Incremental Cost of Delivering PrEP as a Bridge to ART for HIV Serodiscordant Couples in Public HIV Care Clinics in Kenya", "https://www.hindawi.com/journals/art/2019/4170615/", "2019", "Centre for Clinical Research, Kenya Medical Research Institute",
 
"The Effect of Human Immunodeficiency Virus Prevention and Reproductive Health Text Messages on Human Immunodeficiency Virus Testing Among Young Women in Rural Kenya", "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4874231/", "2016", "Centre for Clinical Research, Kenya Medical Research Institute"
  
  
)


publications %>%
  select(Year, `Affiliated institution`, Publication, everything()) %>% 
  reactable::reactable(
    searchable = FALSE,
    pagination = TRUE,
    language = reactableLang(
    searchPlaceholder = "Filter",
    ),
    columns = list(
      Publication = colDef(
        minWidth = 450,
        cell = function(value, index) {
          url_in <- publications$url[index]
          htmltools::a(href = url_in, value)
        }
      ),
      url = colDef(show = FALSE),
      `Affiliated institution` = colDef(minWidth = 200)
    ),
    theme = reactableTheme(
      borderColor = "steelblue",
      stripedColor = "grey",
      highlightColor = "blue",
      cellPadding = "8px 12px",
      style = list(fontFamily = "-apple-system, Lato, sans-serif",
        fontSize = "16px"),
    )
  )

```


## Authored conference papers

```{r}

conference_papers <- tibble::tribble(
  ~Publication, ~url, ~Year, ~ `Affiliated institution`,
  
  "Prevalence and risk factors of hypertension among patients with X-linked hypophosphatemia", "https://ora.ox.ac.uk/objects/uuid:48eaa10e-2663-47a6-ac82-ddab1b1f8910", "2023", "University of Oxford",
  
 "Prevalence of cardiovascular disease events and determinants in patients with X-Linked Hypophosphatemia", "https://www.ndorms.ox.ac.uk/publications/1338095", "2023", "University of Oxford",
 
 
 "Innovative open source approaches to automating clinical data management for a large multi-centre cohort study.", "chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.eahealth.org/sites/www.eahealth.org/files/content/attachments/2019-10-07/Book%20of%20Abstracts%202019_FINAL_FINAL.pdf", "2018", "KEMRI-Wellcome KEMRI-Wellcome Trust Research Programme")


conference_papers %>%
  select(Year, `Affiliated institution`, Publication, everything()) %>% 
  reactable::reactable(
    searchable = FALSE,
    pagination = TRUE,
    language = reactableLang(
    searchPlaceholder = "Filter",
    ),
    columns = list(
      Publication = colDef(
        minWidth = 450,
        cell = function(value, index) {
          url_in <- conference_papers$url[index]
          htmltools::a(href = url_in, value)
        }
      ),
      url = colDef(show = FALSE),
      `Affiliated institution` = colDef(minWidth = 200)
    ),
    theme = reactableTheme(
      borderColor = "steelblue",
      stripedColor = "grey",
      highlightColor = "blue",
      cellPadding = "8px 12px",
      style = list(fontFamily = "-apple-system, Lato, sans-serif",
        fontSize = "16px"),)
  )

```













