<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2023-10-31">

<title>Christopher Maronga - Web scraping using R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="../../site_libs/core-js-2.5.3/shim.min.js"></script>
<script src="../../site_libs/react-17.0.0/react.min.js"></script>
<script src="../../site_libs/react-17.0.0/react-dom.min.js"></script>
<script src="../../site_libs/reactwidget-1.0.0/react-tools.js"></script>
<script src="../../site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<link href="../../site_libs/reactable-0.4.4/reactable.css" rel="stylesheet">
<script src="../../site_libs/reactable-binding-0.4.4/reactable.js"></script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Christopher Maronga</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../talks/talks.html" rel="" target="">
 <span class="menu-text">Talks</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publications/publications.html" rel="" target="">
 <span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../documents/Christopher_Maronga_Resume.pdf" rel="" target="">
 <span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/cmaronga/codecraft.blog" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/krissianyo" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Web scraping using R</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Data mining</div>
                <div class="quarto-category">Data wrangling</div>
                <div class="quarto-category">tidyverse</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">October 31, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#using-rvest" id="toc-using-rvest" class="nav-link" data-scroll-target="#using-rvest">using <code>rvest</code></a>
  <ul>
  <li><a href="#dollar-exchange-data" id="toc-dollar-exchange-data" class="nav-link" data-scroll-target="#dollar-exchange-data">Dollar exchange data</a></li>
  <li><a href="#available-cran-packages" id="toc-available-cran-packages" class="nav-link" data-scroll-target="#available-cran-packages">Available CRAN packages</a>
  <ul class="collapse">
  <li><a href="#cran-packages-by-publication-date" id="toc-cran-packages-by-publication-date" class="nav-link" data-scroll-target="#cran-packages-by-publication-date">CRAN packages by publication date</a></li>
  <li><a href="#cran-packages-metadata" id="toc-cran-packages-metadata" class="nav-link" data-scroll-target="#cran-packages-metadata">CRAN packages metadata</a></li>
  <li><a href="#cran-packages-downloads" id="toc-cran-packages-downloads" class="nav-link" data-scroll-target="#cran-packages-downloads">CRAN packages downloads</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#manually-using-readlines" id="toc-manually-using-readlines" class="nav-link" data-scroll-target="#manually-using-readlines">Manually using <code>readLines()</code></a>
  <ul>
  <li><a href="#read-the-webpage" id="toc-read-the-webpage" class="nav-link" data-scroll-target="#read-the-webpage"><strong>Read the webpage</strong></a></li>
  <li><a href="#search-for-data-bounds" id="toc-search-for-data-bounds" class="nav-link" data-scroll-target="#search-for-data-bounds"><strong>Search for data bounds</strong></a></li>
  <li><a href="#define-whole-data-bounds" id="toc-define-whole-data-bounds" class="nav-link" data-scroll-target="#define-whole-data-bounds"><strong>Define whole data bounds</strong></a></li>
  <li><a href="#cleanup-process" id="toc-cleanup-process" class="nav-link" data-scroll-target="#cleanup-process"><strong>Cleanup process</strong></a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>Efficient, flexible and powerful!</p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Web scraping is concept that most probably you have heard about. This is the art of <a href="https://en.wikipedia.org/wiki/Web_scraping">harvesting</a> publicly available data from a website for use in your analysis or reporting. Web scraping can be as simple as copying the contents of a website and pasting them on an excel sheet, but that’s not what we are going to do today. Most website pages are built using <a href="https://en.wikipedia.org/wiki/HTML">HTML</a> and this allows us to use tools such as R to dynamically extract the data.</p>
<p>In this tutorial, I am going walk you through how you can harvest data from websites using R programming language. You can do this by coding the logic and instructions manually or use the package <a href="https://rvest.tidyverse.org/"><code>{rvest}</code></a> to easily extract the contents of a website. We would demonstrate the examples using the below two websites.</p>
<ul>
<li>TheGlobalEconomy.com, <a href="https://www.theglobaleconomy.com/rankings/Dollar_exchange_rate/">Exchange rate to USD by country</a></li>
<li><a href="https://cran.r-project.org/web/packages/available_packages_by_date.html">CRAN package</a> website and <a href="https://www.datasciencemeta.com/rpackages">package download metrics</a> website</li>
</ul>
<p>First, let’s load the packages/tools of trade for the exercise.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loading packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  rvest,        <span class="co"># functions for webscraping</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  ggthemes,     <span class="co"># extend themes for ggplot2</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  lubridate,    <span class="co"># handle dates</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  here,         <span class="co"># manage file paths</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  flextable,    <span class="co"># quick tables</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  tidyverse     <span class="co"># data wranglinga and visualization</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># set theme for ggplot2</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_hc</span>(<span class="at">base_size =</span> <span class="dv">18</span>) <span class="sc">+</span>                  <span class="co"># base size</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position =</span> <span class="st">"none"</span>,              <span class="co"># No legend, unless specified in the plot</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),         <span class="co"># No title on the legend</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>) <span class="co"># spin y title 90 degrees</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="using-rvest" class="level1">
<h1>using <code>rvest</code></h1>
<p>This is the simplest and easiest approach of then all. <a href="https://rvest.tidyverse.org/">rvest helps you scrape (or harvest)</a> data from web pages and it’s designed to work with the pipe chain style of coding.</p>
<p>Three simples steps using this package:-</p>
<ul>
<li>Use <code>read_tml</code> function to convert the the url into an <code>xml document</code></li>
<li>pass the <code>xlm document</code> to the function <code>html_table</code> to convert it into a list contain table(s) from the url source site.</li>
<li>Now that you have tabular data, you can proceed with various data wrangling approaches to clean it up for use.</li>
</ul>
<section id="dollar-exchange-data" class="level2">
<h2 class="anchored" data-anchor-id="dollar-exchange-data">Dollar exchange data</h2>
<p>I came across this website <a href="https://www.theglobaleconomy.com/rankings/Dollar_exchange_rate/">Exchange rate to USD by country</a> while I was working on aggregating output from an<a href="https://asbmr.onlinelibrary.wiley.com/doi/full/10.1002/jbmr.4775?af=R">economic micro-simulation model</a> estimating benefits and budget impact of setting up fracture liaison services. Part of my reporting costs associated with the FLS, reported in local currency for about 10 different countries, but for harmonized reporting and international consumption, I need to convert the local currencies to US Dollars, hence I needed a source that I could cite and is updated regularly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get url from website</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>exchange_rate_url <span class="ot">&lt;-</span> <span class="st">"https://www.theglobaleconomy.com/rankings/Dollar_exchange_rate/"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># read HTML from website</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>exchange_rate_webpage <span class="ot">&lt;-</span> <span class="fu">read_html</span>(exchange_rate_url)       <span class="co"># read html site</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># create a datframe containing the exchange rates for use</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>currency_rates <span class="ot">&lt;-</span> exchange_rate_webpage <span class="sc">%&gt;%</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">html_table</span>() <span class="sc">%&gt;%</span>                                          <span class="co"># output a list contain the exchange rate table from website</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span>                                       <span class="co"># transform into a tibble</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># rename columns appropriately</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">Country        =</span> Countries,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">LatestData     =</span> <span class="st">"Reference.date"</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">LatesValue     =</span> <span class="st">"Latest.available.value"</span>,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">Change3months  =</span> <span class="st">"Change.three.months"</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">Change12months =</span> <span class="st">"Change.twelve.months"</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(LatesValue, as.numeric),                  <span class="co"># convert to numeric column containing exchange rate</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>         </span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>         <span class="co"># On the date column; remove white space and replace "/" with "-"</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>         <span class="at">LatestData =</span> <span class="fu">str_squish</span>(</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>           <span class="fu">str_replace_all</span>(</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>             <span class="at">string =</span> LatestData,</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>             <span class="at">pattern =</span> <span class="st">"/"</span>,</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>             <span class="at">replacement =</span> <span class="st">"-"</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>         )) <span class="sc">%&gt;%</span> </span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># transform `LatestData` into a proper date column</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">LatestData =</span> <span class="fu">my</span>(LatestData),                       <span class="co"># proper date format</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">LatestData =</span> <span class="fu">format</span>(LatestData, <span class="st">"%Y-%m"</span>)           <span class="co"># YYYY-mm</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The first 15 rows of the harvested data are show below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>currency_rates <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Country LatesValue LatestData Change3months Change12months
1          Afghanistan    75.4778    2023-10       -13.35%        -13.07%
2              Albania   100.1403    2023-10         6.77%        -15.96%
3              Algeria   137.2571    2023-10         1.59%         -2.22%
4              Andorra     0.9466    2023-10         4.67%         -6.90%
5               Angola   828.1470    2023-10         0.28%         83.55%
6  Antigua and Barbuda     2.7026    2023-10         0.00%          0.00%
7            Argentina   349.9246    2023-10        31.68%        130.05%
8              Armenia   402.5164    2023-10         4.31%          0.08%
9                Aruba     1.8011    2023-10        -0.03%          0.01%
10           Australia     1.5759    2023-10         6.05%          0.25%
11             Austria     0.9466    2023-10         4.67%         -6.90%
12          Azerbaijan     1.7000    2023-10         0.00%          0.00%
13             Bahamas     0.9995    2023-10         0.10%         -0.01%
14             Bahrain     0.3767    2023-10         0.05%         -0.13%
15          Bangladesh   110.1738    2023-10         1.65%          7.81%</code></pre>
</div>
</div>
<p>You can now export the harvested data for later use downstream or in your modelling framework like I did. You see, easy and straight forward, right?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Export the data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>rio<span class="sc">::</span><span class="fu">export</span>(currency_rates, <span class="fu">here</span>(<span class="st">"datasets"</span>, <span class="st">"dollar_exchange_rates.rds"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="available-cran-packages" class="level2">
<h2 class="anchored" data-anchor-id="available-cran-packages">Available CRAN packages</h2>
<p>In this section, we are going to harvest data from two websites:-</p>
<ul>
<li>List of available <a href="https://cran.r-project.org/web/packages/available_packages_by_date.html">CRAN packages</a> by data of publication</li>
<li>Tracked website of <a href="https://www.datasciencemeta.com/rpackages">CRAN packages by number of downloads</a></li>
<li>Additionally, to get some metrics to combine with data from the above 2 sites, we I use <code>available.packages</code> function for all cran packages in this <a href="https://cran.r-project.org/">mirror</a></li>
</ul>
<section id="cran-packages-by-publication-date" class="level3">
<h3 class="anchored" data-anchor-id="cran-packages-by-publication-date">CRAN packages by publication date</h3>
<p>I will use the 3 simple steps already covered earlier, employing <code>rvest</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specifying the url</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">'https://cran.r-project.org/web/packages/available_packages_by_date.html'</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># create a dataframe using `rvest` functions</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>r_pkgs_by_date <span class="ot">&lt;-</span> <span class="fu">read_html</span>(url) <span class="sc">%&gt;%</span> </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">html_table</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Date =</span> <span class="fu">ymd</span>(Date)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">pkg_name =</span> Package, <span class="at">date_published =</span> Date)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co"># view top n rows</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>r_pkgs_by_date <span class="sc">%&gt;%</span> </span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   date_published      pkg_name
1      2023-11-03           abn
2      2023-11-03          afpt
3      2023-11-03     betaDelta
4      2023-11-03          bild
5      2023-11-03     chisquare
6      2023-11-03           DPQ
7      2023-11-03 DTRKernSmooth
8      2023-11-03       fBasics
9      2023-11-03     FieldSimR
10     2023-11-03     GOxploreR
                                                                                                       Title
1                                                Modelling Multivariate Data with Additive Bayesian Networks
2                                                           Tools for Modelling of Animal Flight Performance
3                                              Confidence Intervals for Standardized Regression Coefficients
4                                                                     A Package for BInary Longitudinal Data
5  Chi-Square and G-Square Test of Independence, Residual Analysis,\nand Measures of Categorical Association
6                                                        Density, Probability, Quantile ('DPQ') Computations
7                          Estimate and Make Inference About Optimal Treatment Regimes via\nSmoothed Methods
8                                                                    Rmetrics - Markets and Basic Statistics
9                                   Simulation of Plot Errors and Phenotypes in Plant Breeding Field\nTrials
10                                           Structural Exploration of the Gene Ontology (GO) Knowledge Base</code></pre>
</div>
</div>
</section>
<section id="cran-packages-metadata" class="level3">
<h3 class="anchored" data-anchor-id="cran-packages-metadata">CRAN packages metadata</h3>
<p>If I need additional details, I can use the function <code>available.packages()</code>; downside, it doesn’t contain date of publication, but some other metrics which are equally important are returned by this function. So, I ma going to do that below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># using available.packages function</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>available_pks <span class="ot">&lt;-</span> <span class="fu">available.packages</span>(<span class="co">#repos = "http://cran.us.r-project.org",</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                                                                            <span class="co"># specify CRAN mirror and metadata to extract</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">repos =</span> <span class="st">"https://cran.r-project.org/"</span>)[, <span class="fu">c</span>(<span class="st">"Version"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                                             <span class="st">"Depends"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>                                             <span class="st">"Repository"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                                             <span class="st">"NeedsCompilation"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>                                             <span class="st">"License"</span>)] <span class="sc">%&gt;%</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span> tibble<span class="sc">::</span><span class="fu">rownames_to_column</span>(<span class="at">var =</span> <span class="st">"pkg_name"</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># view top n rows</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>available_pks <span class="sc">%&gt;%</span> </span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        pkg_name Version                                             Depends
1             A3   1.0.0                      R (&gt;= 2.15.0), xtable, pbapply
2  AalenJohansen     1.0                                                &lt;NA&gt;
3       AATtools   0.0.2                                        R (&gt;= 3.6.0)
4         ABACUS   1.0.0                                        R (&gt;= 3.1.0)
5    abasequence   0.1.0                                                &lt;NA&gt;
6     abbreviate     0.1                                                &lt;NA&gt;
7            abc   2.2.1 R (&gt;= 2.10), abc.data, nnet, quantreg, MASS, locfit
8       abc.data     1.0                                         R (&gt;= 2.10)
9        ABC.RAP   0.9.0                                        R (&gt;= 3.1.0)
10   ABCanalysis   1.2.1                                         R (&gt;= 2.10)
                               Repository NeedsCompilation    License
1  https://cran.r-project.org/src/contrib               no GPL (&gt;= 2)
2  https://cran.r-project.org/src/contrib               no GPL (&gt;= 2)
3  https://cran.r-project.org/src/contrib               no      GPL-3
4  https://cran.r-project.org/src/contrib               no      GPL-3
5  https://cran.r-project.org/src/contrib               no      GPL-3
6  https://cran.r-project.org/src/contrib               no      GPL-3
7  https://cran.r-project.org/src/contrib               no GPL (&gt;= 3)
8  https://cran.r-project.org/src/contrib               no GPL (&gt;= 3)
9  https://cran.r-project.org/src/contrib               no      GPL-3
10 https://cran.r-project.org/src/contrib               no      GPL-3</code></pre>
</div>
</div>
</section>
<section id="cran-packages-downloads" class="level3">
<h3 class="anchored" data-anchor-id="cran-packages-downloads">CRAN packages downloads</h3>
<p>We can grab metric on number of downloads for each package in CRAN from this <a href="https://www.datasciencemeta.com/rpackages">website.</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>pkg_down_url <span class="ot">&lt;-</span> <span class="st">"https://www.datasciencemeta.com/rpackages"</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>pkg_downloads <span class="ot">&lt;-</span> <span class="fu">read_html</span>(pkg_down_url) <span class="sc">%&gt;%</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">html_table</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(Author, Maintainer)) <span class="sc">%&gt;%</span>                          <span class="co"># remove columns with no data</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Downloads =</span> <span class="fu">str_remove_all</span>(Downloads, <span class="at">pattern =</span> <span class="st">","</span>),     <span class="co"># get rid of commas</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Downloads =</span> <span class="fu">as.integer</span>(Downloads)                         <span class="co"># convert into an integer</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">pkg_name =</span> <span class="st">"Package.Name"</span>, <span class="at">downloads =</span> Downloads)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co"># view top n rows</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>pkg_downloads <span class="sc">%&gt;%</span> </span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Rank pkg_name downloads
1     1  ggplot2 127088264
2     2    rlang 118170119
3     3 magrittr 115906264
4     4    dplyr  96514386
5     5    vctrs  84215499
6     6   tibble  81744821
7     7      cli  80994837
8     8 devtools  80226146
9     9 jsonlite  79806265
10   10   pillar  76393888</code></pre>
</div>
</div>
<p>Here is the fun part, we can now join all the three datasets telling different aspects of the packages to have one dataframe we can use for visualization and expropriation, how cool is that🙂</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>CRAN_pkgs <span class="ot">&lt;-</span> <span class="fu">reduce</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(r_pkgs_by_date, pkg_downloads, available_pks), <span class="co"># reduce from purrr package</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  left_join,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="st">"pkg_name"</span>                                     <span class="co"># join by package_name</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(Rank) <span class="sc">%&gt;%</span> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Rank, pkg_name, downloads, <span class="fu">everything</span>())</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># view top n rows</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>CRAN_pkgs <span class="sc">%&gt;%</span> </span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  reactable<span class="sc">::</span><span class="fu">reactable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div class="reactable html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-4852f58c89c3183ecac6" style="width:auto;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-4852f58c89c3183ecac6">{"x":{"tag":{"name":"Reactable","attribs":{"data":{"Rank":[1,2,3,4,5],"pkg_name":["ggplot2","rlang","magrittr","dplyr","vctrs"],"downloads":[127088264,118170119,115906264,96514386,84215499],"date_published":["2023-10-12","2023-04-28","2022-03-30","2023-09-03","2023-10-12"],"Title":["Create Elegant Data Visualisations Using the Grammar of Graphics","Functions for Base Types and Core R and 'Tidyverse' Features","A Forward-Pipe Operator for R","A Grammar of Data Manipulation","Vector Helpers"],"Version":["3.4.4","1.1.1","2.0.3","1.1.3","0.6.4"],"Depends":["R (>= 3.3)","R (>= 3.5.0)","R (>= 3.4.0)","R (>= 3.5.0)","R (>= 3.5.0)"],"Repository":["https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib"],"NeedsCompilation":["no","yes","yes","yes","yes"],"License":["MIT + file LICENSE","MIT + file LICENSE","MIT + file LICENSE","MIT + file LICENSE","MIT + file LICENSE"]},"columns":[{"id":"Rank","name":"Rank","type":"numeric"},{"id":"pkg_name","name":"pkg_name","type":"character"},{"id":"downloads","name":"downloads","type":"numeric"},{"id":"date_published","name":"date_published","type":"Date"},{"id":"Title","name":"Title","type":"character"},{"id":"Version","name":"Version","type":"character"},{"id":"Depends","name":"Depends","type":"character"},{"id":"Repository","name":"Repository","type":"character"},{"id":"NeedsCompilation","name":"NeedsCompilation","type":"character"},{"id":"License","name":"License","type":"character"}],"dataKey":"78bf2e3e9dbd55091d79de567d7a8911"},"children":[]},"class":"reactR_markup"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>For instance, as of the harvesting of this data, what are the top 20 most downloaded packages from CRAN. We can be able to summarize and visualize that information</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>CRAN_pkgs <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Rank <span class="sc">&lt;=</span> <span class="dv">20</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  reactable<span class="sc">::</span><span class="fu">reactable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div class="reactable html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-a41543dc8d17ed6d353a" style="width:auto;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-a41543dc8d17ed6d353a">{"x":{"tag":{"name":"Reactable","attribs":{"data":{"Rank":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],"pkg_name":["ggplot2","rlang","magrittr","dplyr","vctrs","tibble","cli","devtools","jsonlite","pillar","Rcpp","glue","lifecycle","stringr","stringi","ragg","textshaping","digest","tidyverse","knitr"],"downloads":[127088264,118170119,115906264,96514386,84215499,81744821,80994837,80226146,79806265,76393888,76161093,73824263,71584623,68447620,65611001,64115392,62983902,61962888,61464580,58384350],"date_published":["2023-10-12","2023-04-28","2022-03-30","2023-09-03","2023-10-12","2023-03-20","2023-03-23","2022-10-11","2023-06-29","2023-03-22","2023-07-06","2022-02-24","2022-10-07","2022-12-02","2023-01-11","2023-10-10","2023-10-09","2023-07-07","2023-02-22","2023-10-30"],"Title":["Create Elegant Data Visualisations Using the Grammar of Graphics","Functions for Base Types and Core R and 'Tidyverse' Features","A Forward-Pipe Operator for R","A Grammar of Data Manipulation","Vector Helpers","Simple Data Frames","Helpers for Developing Command Line Interfaces","Tools to Make Developing R Packages Easier","A Simple and Robust JSON Parser and Generator for R","Coloured Formatting for Columns","Seamless R and C++ Integration","Interpreted String Literals","Manage the Life Cycle of your Package Functions","Simple, Consistent Wrappers for Common String Operations","Fast and Portable Character String Processing Facilities","Graphic Devices Based on AGG","Bindings to the 'HarfBuzz' and 'Fribidi' Libraries for Text\nShaping","Create Compact Hash Digests of R Objects","Easily Install and Load the 'Tidyverse'","A General-Purpose Package for Dynamic Report Generation in R"],"Version":["3.4.4","1.1.1","2.0.3","1.1.3","0.6.4","3.2.1","3.6.1","2.4.5","1.8.7","1.9.0","1.0.11","1.6.2","1.0.3","1.5.0","1.7.12","1.2.6","0.3.7","0.6.33","2.0.0","1.45"],"Depends":["R (>= 3.3)","R (>= 3.5.0)","R (>= 3.4.0)","R (>= 3.5.0)","R (>= 3.5.0)","R (>= 3.4.0)","R (>= 3.4)","R (>= 3.0.2), usethis (>= 2.1.6)","methods",null,null,"R (>= 3.4)","R (>= 3.4)","R (>= 3.3)","R (>= 3.1)",null,"R (>= 3.2.0)","R (>= 3.3.0)","R (>= 3.3)","R (>= 3.3.0)"],"Repository":["https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib","https://cran.r-project.org/src/contrib"],"NeedsCompilation":["no","yes","yes","yes","yes","yes","yes","no","yes","no","yes","yes","no","no","yes","yes","yes","yes","no","no"],"License":["MIT + file LICENSE","MIT + file LICENSE","MIT + file LICENSE","MIT + file LICENSE","MIT + file LICENSE","MIT + file LICENSE","MIT + file LICENSE","MIT + file LICENSE","MIT + file LICENSE","MIT + file LICENSE","GPL (>= 2)","MIT + file LICENSE","MIT + file LICENSE","MIT + file LICENSE","file LICENSE","MIT + file LICENSE","MIT + file LICENSE","GPL (>= 2)","MIT + file LICENSE","GPL"]},"columns":[{"id":"Rank","name":"Rank","type":"numeric"},{"id":"pkg_name","name":"pkg_name","type":"character"},{"id":"downloads","name":"downloads","type":"numeric"},{"id":"date_published","name":"date_published","type":"Date"},{"id":"Title","name":"Title","type":"character"},{"id":"Version","name":"Version","type":"character"},{"id":"Depends","name":"Depends","type":"character"},{"id":"Repository","name":"Repository","type":"character"},{"id":"NeedsCompilation","name":"NeedsCompilation","type":"character"},{"id":"License","name":"License","type":"character"}],"dataKey":"d72049164000c3f8f5b19f242a888ae4"},"children":[]},"class":"reactR_markup"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>More fun exploration and data wrangling can be performed on the harvested data, feel free to play with the data further.</p>
<p>Export the combined dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># export data for playing around with</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>rio<span class="sc">::</span><span class="fu">export</span>(CRAN_pkgs, <span class="fu">here</span>(<span class="st">"datasets"</span>, <span class="st">"CRAN_pkgs.rds"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="manually-using-readlines" class="level1">
<h1>Manually using <code>readLines()</code></h1>
<p>Sometimes, not all websites are structured in the manner that the dollar exchange website is. What this means is that the magic of the two functions above (<code>read_html</code> and <code>html_tabel</code>) do not work as expected.</p>
<p>In such scenarios, I am going to show you a manual way to still harvest data using the <code>readLines</code> functions. I must admit that this is a very painful approach and is NOT standard nor reproducible as it depends on the state/structure of the website at the time of harvesting.</p>
<section id="read-the-webpage" class="level4">
<h4 class="anchored" data-anchor-id="read-the-webpage"><strong>Read the webpage</strong></h4>
<p>The first step is to read the html code from the website using <code>readLines</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># store url link</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>dollar_ex_url <span class="ot">&lt;-</span> <span class="st">"https://www.theglobaleconomy.com/rankings/Dollar_exchange_rate/"</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Reading the HTML code from the website</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>dollaEx_webpage <span class="ot">&lt;-</span> <span class="fu">readLines</span>(dollar_ex_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in readLines(dollar_ex_url): incomplete final line found on
'https://www.theglobaleconomy.com/rankings/Dollar_exchange_rate/'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dollaEx_webpage, <span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "&lt;!DOCTYPE html&gt;"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 [2] "&lt;html xmlns='https://www.w3.org/1999/xhtml' lang=\"en\" xml:lang='en' &gt;"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 [3] "\t&lt;head&gt;"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 [4] "\t\t&lt;meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0\"/&gt;"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 [5] "\t\t"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 [6] "\t\t&lt;link rel=\"canonical\" href=\"https://www.theglobaleconomy.com/rankings/Dollar_exchange_rate/\"&gt;"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 [7] "\t\t"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 [8] "\t\t\t\t&lt;meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" /&gt;"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
 [9] "\t\t"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
[10] "\t\t&lt;link rel=\"shortcut icon\" href=\"/favicon.ico\" type=\"image/x-icon\"&gt;"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
[11] "\t\t&lt;link rel=\"icon\" href=\"/favicon.ico\" type=\"image/x-icon\"&gt;"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
[12] "\t\t"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
[13] "\t\t&lt;title&gt;Exchange rate to USD around the world | TheGlobalEconomy.com&lt;/title&gt;"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
[14] "\t\t&lt;meta name=\"Keywords\" content=\"Exchange rate to USD around the world\" /&gt;"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
[15] "\t\t&lt;meta name=\"Description\" content=\"What do we see on the table: June 2022 update Several countries, including Yemen, Sri Lanka, and Belarus experienced sizable depreciation again the dollar in the last three months. In contrast, the Russian ruble strengthened against the dollar. Over the last three months to May 2022, the dollar appreciated against the euro by about 7 percent, 12 percent against the Japanese yen and about 8 percent against the British pound. In short, the dollar has gained value against all major currencies. It also gained on the Chinese renminbi and the Indian rupee but lost some ground to the Brazilian real. What factors determine the exchange rates The exchange rate is the price of one currency expressed in units of another currency. We say that a currency is appreciating/depreciating relative to another currency if … continue reading below the table \" /&gt;"</code></pre>
</div>
</div>
<p>The <code>dollaEx_webpage</code> is basically a HTML page with all the usual html tags and stuff. So, we are going refer to the website for a start point to give us reference for first entry and last entry of the page. From experience, I have found focusing on the actual data saves time and very easy to proceed forth as opposed to randomly picking any entry on the page.</p>
<p>For instance, Afghanistan is the first entry on the table and Zambia is the last entry, this gives me an idea of the bound of the data that I want. Ideally I need everything between entry one and last entry and I am going to show you how.</p>
</section>
<section id="search-for-data-bounds" class="level4">
<h4 class="anchored" data-anchor-id="search-for-data-bounds"><strong>Search for data bounds</strong></h4>
<p>Now, the manual work starts here. From the source website, I want to find the index or indices of <code>Afghanistan</code>, my first data point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_which</span>(dollaEx_webpage, <span class="st">"Afghanistan"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 922</code></pre>
</div>
</div>
<p>What this means is that the key word Afghanistan has been found in position 922 (sometimes multiple positions get returned). We can try to triangulate around these positions and see what we’ve got going. There is not rule for triangulation, you just throw the net and inspect the output, that’s why it’s a manual approach.</p>
<p>From the <code>dollaEx_webpage</code> object and with the index of my first data point, I start the triangulation process. For instance, let me view the next 10 lines after position <code>922</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dollaEx_webpage[<span class="dv">922</span><span class="sc">:</span><span class="dv">932</span>] <span class="co"># first 10 lines</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "\t\t\t\t\t\t&lt;td&gt;&lt;a href='/Afghanistan/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Afghanistan&lt;/a&gt;&lt;/td&gt;"
 [2] "\t\t\t\t\t\t&lt;td&gt;75.4778&lt;/td&gt;"                                                                           
 [3] "\t\t\t\t\t\t&lt;td&gt;Oct / 2023&lt;/td&gt;"                                                                        
 [4] "\t\t\t\t\t\t\t\t\t\t\t\t&lt;td&gt;-13.35%&lt;/td&gt;"                                                               
 [5] "\t\t\t\t\t\t&lt;td&gt;-13.07%&lt;/td&gt;"                                                                           
 [6] "\t\t\t\t\t\t\t\t\t\t\t&lt;/tr&gt;"                                                                            
 [7] "\t\t\t\t\t\t\t\t\t&lt;tr&gt;"                                                                                 
 [8] "\t\t\t\t\t\t&lt;td&gt;&lt;a href='/Albania/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Albania&lt;/a&gt;&lt;/td&gt;"        
 [9] "\t\t\t\t\t\t&lt;td&gt;100.1403&lt;/td&gt;"                                                                          
[10] "\t\t\t\t\t\t&lt;td&gt;Oct / 2023&lt;/td&gt;"                                                                        
[11] "\t\t\t\t\t\t\t\t\t\t\t\t&lt;td&gt;6.77%&lt;/td&gt;"                                                                 </code></pre>
</div>
</div>
<p>Clearly from the above output, if I were interested in data for <code>Afghanistan</code> only, i.e.&nbsp;the 5 columns from the table in the website, they are contained between positions 922 and 926, see below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dollaEx_webpage[<span class="dv">922</span><span class="sc">:</span><span class="dv">926</span>] </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "\t\t\t\t\t\t&lt;td&gt;&lt;a href='/Afghanistan/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Afghanistan&lt;/a&gt;&lt;/td&gt;"
[2] "\t\t\t\t\t\t&lt;td&gt;75.4778&lt;/td&gt;"                                                                           
[3] "\t\t\t\t\t\t&lt;td&gt;Oct / 2023&lt;/td&gt;"                                                                        
[4] "\t\t\t\t\t\t\t\t\t\t\t\t&lt;td&gt;-13.35%&lt;/td&gt;"                                                               
[5] "\t\t\t\t\t\t&lt;td&gt;-13.07%&lt;/td&gt;"                                                                           </code></pre>
</div>
</div>
<p><strong>NOTE</strong>, I am ONLY interested at the start and end of the data string containing the columns a.ka. data that I need. Do the same for the last entry on the table (in the website), which in this case is <code>Zambia.</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Last entry</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str_which</span>(dollaEx_webpage, <span class="st">"Zambia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2252</code></pre>
</div>
</div>
<p>NOTE, I am interested at the start and end of the data string. The index for Zambia is 2252, based on what I did with the first entry on the table, it simply means that the data bound for Zambia is contained within 4 steps/lines from 2252. See below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>dollaEx_webpage[<span class="dv">2252</span><span class="sc">:</span><span class="dv">2256</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "\t\t\t\t\t\t&lt;td&gt;&lt;a href='/Zambia/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Zambia&lt;/a&gt;&lt;/td&gt;"
[2] "\t\t\t\t\t\t&lt;td&gt;21.5142&lt;/td&gt;"                                                                 
[3] "\t\t\t\t\t\t&lt;td&gt;Oct / 2023&lt;/td&gt;"                                                              
[4] "\t\t\t\t\t\t\t\t\t\t\t\t&lt;td&gt;16.24%&lt;/td&gt;"                                                      
[5] "\t\t\t\t\t\t&lt;td&gt;35.05%&lt;/td&gt;"                                                                  </code></pre>
</div>
</div>
<p>After carefully inspecting the above outputs, I can conclude that the data I am looking for (the whole table) lies between 922 to 2256. Anything before or after contain nothing other than “ tags only.</p>
</section>
<section id="define-whole-data-bounds" class="level4">
<h4 class="anchored" data-anchor-id="define-whole-data-bounds"><strong>Define whole data bounds</strong></h4>
<p>After arriving at this conclusion, then next step is to now narrow your webpage to the data bounds only i.e.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># resize your webpage to only contain the data</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>dollaEx_webData <span class="ot">&lt;-</span> dollaEx_webpage[<span class="dv">922</span><span class="sc">:</span><span class="dv">2256</span>]</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dollaEx_webData, <span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "\t\t\t\t\t\t&lt;td&gt;&lt;a href='/Afghanistan/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Afghanistan&lt;/a&gt;&lt;/td&gt;"
 [2] "\t\t\t\t\t\t&lt;td&gt;75.4778&lt;/td&gt;"                                                                           
 [3] "\t\t\t\t\t\t&lt;td&gt;Oct / 2023&lt;/td&gt;"                                                                        
 [4] "\t\t\t\t\t\t\t\t\t\t\t\t&lt;td&gt;-13.35%&lt;/td&gt;"                                                               
 [5] "\t\t\t\t\t\t&lt;td&gt;-13.07%&lt;/td&gt;"                                                                           
 [6] "\t\t\t\t\t\t\t\t\t\t\t&lt;/tr&gt;"                                                                            
 [7] "\t\t\t\t\t\t\t\t\t&lt;tr&gt;"                                                                                 
 [8] "\t\t\t\t\t\t&lt;td&gt;&lt;a href='/Albania/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Albania&lt;/a&gt;&lt;/td&gt;"        
 [9] "\t\t\t\t\t\t&lt;td&gt;100.1403&lt;/td&gt;"                                                                          
[10] "\t\t\t\t\t\t&lt;td&gt;Oct / 2023&lt;/td&gt;"                                                                        
[11] "\t\t\t\t\t\t\t\t\t\t\t\t&lt;td&gt;6.77%&lt;/td&gt;"                                                                 
[12] "\t\t\t\t\t\t&lt;td&gt;-15.96%&lt;/td&gt;"                                                                           
[13] "\t\t\t\t\t\t\t\t\t\t\t&lt;/tr&gt;"                                                                            
[14] "\t\t\t\t\t\t\t\t\t&lt;tr&gt;"                                                                                 
[15] "\t\t\t\t\t\t&lt;td&gt;&lt;a href='/Algeria/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Algeria&lt;/a&gt;&lt;/td&gt;"        </code></pre>
</div>
</div>
<p>If you widely look at the object <code>dollaEx_webData</code>, it contains a lot of unnecessary “ tags, so now it’s time to clean this object carefully ind order to obtain the data.</p>
</section>
<section id="cleanup-process" class="level4">
<h4 class="anchored" data-anchor-id="cleanup-process"><strong>Cleanup process</strong></h4>
<p>First get rid of all the <code>"\t\t\t\t\t\t\t\t\t\t\t\t\t"</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove ALL the "\t"</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dollaEx_clean <span class="ot">&lt;-</span> dollaEx_webData <span class="sc">%&gt;%</span> <span class="fu">str_remove_all</span>(<span class="at">pattern =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dollaEx_clean,<span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "&lt;td&gt;&lt;a href='/Afghanistan/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Afghanistan&lt;/a&gt;&lt;/td&gt;"
 [2] "&lt;td&gt;75.4778&lt;/td&gt;"                                                                           
 [3] "&lt;td&gt;Oct / 2023&lt;/td&gt;"                                                                        
 [4] "&lt;td&gt;-13.35%&lt;/td&gt;"                                                                           
 [5] "&lt;td&gt;-13.07%&lt;/td&gt;"                                                                           
 [6] "&lt;/tr&gt;"                                                                                      
 [7] "&lt;tr&gt;"                                                                                       
 [8] "&lt;td&gt;&lt;a href='/Albania/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Albania&lt;/a&gt;&lt;/td&gt;"        
 [9] "&lt;td&gt;100.1403&lt;/td&gt;"                                                                          
[10] "&lt;td&gt;Oct / 2023&lt;/td&gt;"                                                                        
[11] "&lt;td&gt;6.77%&lt;/td&gt;"                                                                             
[12] "&lt;td&gt;-15.96%&lt;/td&gt;"                                                                           
[13] "&lt;/tr&gt;"                                                                                      
[14] "&lt;tr&gt;"                                                                                       
[15] "&lt;td&gt;&lt;a href='/Algeria/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Algeria&lt;/a&gt;&lt;/td&gt;"        
[16] "&lt;td&gt;137.2571&lt;/td&gt;"                                                                          
[17] "&lt;td&gt;Oct / 2023&lt;/td&gt;"                                                                        
[18] "&lt;td&gt;1.59%&lt;/td&gt;"                                                                             
[19] "&lt;td&gt;-2.22%&lt;/td&gt;"                                                                            
[20] "&lt;/tr&gt;"                                                                                      
[21] "&lt;tr&gt;"                                                                                       
[22] "&lt;td&gt;&lt;a href='/Andorra/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Andorra&lt;/a&gt;&lt;/td&gt;"        
[23] "&lt;td&gt;0.9466&lt;/td&gt;"                                                                            
[24] "&lt;td&gt;Oct / 2023&lt;/td&gt;"                                                                        
[25] "&lt;td&gt;4.67%&lt;/td&gt;"                                                                             </code></pre>
</div>
</div>
<p>The object <code>dollaEx_webData</code> basically contains unique strings that contain data from the column of the table in the <code>url.</code> If you look closely, you will see a recurring pattern of strings, each starting with <code>""&lt;td&gt;&lt;a href='/"</code>and ending with a double <code>"&lt;/tr&gt;"</code>; and ideally, this is the trick. The ability to understand the output and content of <code>dollaEx_clean.</code></p>
<p>If you then count these start and end of recurring patterns, you find that they are 7 in number, so a single country data is composed of 7 unique strings Try viewing the first 25 rows of <code>dollaEx_clean</code>, you will be able to see what I mean.</p>
<p>Take these unique strings and turn them into a matrix with each column containing the vital pieces of information and drop what is NOT required.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>dollaEx_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(dollaEx_clean, </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">ncol =</span> <span class="dv">7</span>, <span class="co"># 7 columns because there were 7 unique strings</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in matrix(dollaEx_clean, ncol = 7, byrow = TRUE): data length [1335] is
not a sub-multiple or multiple of the number of rows [191]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dollaEx_matrix, <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]                                                                                         
[1,] "&lt;td&gt;&lt;a href='/Afghanistan/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Afghanistan&lt;/a&gt;&lt;/td&gt;"
[2,] "&lt;td&gt;&lt;a href='/Albania/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Albania&lt;/a&gt;&lt;/td&gt;"        
[3,] "&lt;td&gt;&lt;a href='/Algeria/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Algeria&lt;/a&gt;&lt;/td&gt;"        
[4,] "&lt;td&gt;&lt;a href='/Andorra/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Andorra&lt;/a&gt;&lt;/td&gt;"        
     [,2]                [,3]                  [,4]              
[1,] "&lt;td&gt;75.4778&lt;/td&gt;"  "&lt;td&gt;Oct / 2023&lt;/td&gt;" "&lt;td&gt;-13.35%&lt;/td&gt;"
[2,] "&lt;td&gt;100.1403&lt;/td&gt;" "&lt;td&gt;Oct / 2023&lt;/td&gt;" "&lt;td&gt;6.77%&lt;/td&gt;"  
[3,] "&lt;td&gt;137.2571&lt;/td&gt;" "&lt;td&gt;Oct / 2023&lt;/td&gt;" "&lt;td&gt;1.59%&lt;/td&gt;"  
[4,] "&lt;td&gt;0.9466&lt;/td&gt;"   "&lt;td&gt;Oct / 2023&lt;/td&gt;" "&lt;td&gt;4.67%&lt;/td&gt;"  
     [,5]               [,6]    [,7]  
[1,] "&lt;td&gt;-13.07%&lt;/td&gt;" "&lt;/tr&gt;" "&lt;tr&gt;"
[2,] "&lt;td&gt;-15.96%&lt;/td&gt;" "&lt;/tr&gt;" "&lt;tr&gt;"
[3,] "&lt;td&gt;-2.22%&lt;/td&gt;"  "&lt;/tr&gt;" "&lt;tr&gt;"
[4,] "&lt;td&gt;-6.90%&lt;/td&gt;"  "&lt;/tr&gt;" "&lt;tr&gt;"</code></pre>
</div>
</div>
<p>The matrix contains 7 columns (7 uniques strings, remember?). Information that we are most interested in (i.e the columns of the table in the url) are contained in the following columns of the matrix.</p>
<ul>
<li>column 1 contains country</li>
<li>column 3 contains latest data from</li>
<li>column 2 contains latest value</li>
<li>column 4 contains change 3 months</li>
<li>column 5 contains change 12 months</li>
</ul>
<p>With this information, we can now construct the final clean matrix by droping column 6 and 7 which contains nothing we are interested in.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># drop columns that don't contain information of interest</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>dollaEx_matrix_clean <span class="ot">&lt;-</span> dollaEx_matrix[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)]</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dollaEx_matrix_clean, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]                                                                                         
[1,] "&lt;td&gt;&lt;a href='/Afghanistan/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Afghanistan&lt;/a&gt;&lt;/td&gt;"
[2,] "&lt;td&gt;&lt;a href='/Albania/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Albania&lt;/a&gt;&lt;/td&gt;"        
[3,] "&lt;td&gt;&lt;a href='/Algeria/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Algeria&lt;/a&gt;&lt;/td&gt;"        
[4,] "&lt;td&gt;&lt;a href='/Andorra/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Andorra&lt;/a&gt;&lt;/td&gt;"        
[5,] "&lt;td&gt;&lt;a href='/Angola/Dollar_exchange_rate/' style=\"color:#000;\"&gt;Angola&lt;/a&gt;&lt;/td&gt;"          
     [,2]                [,3]                  [,4]              
[1,] "&lt;td&gt;75.4778&lt;/td&gt;"  "&lt;td&gt;Oct / 2023&lt;/td&gt;" "&lt;td&gt;-13.35%&lt;/td&gt;"
[2,] "&lt;td&gt;100.1403&lt;/td&gt;" "&lt;td&gt;Oct / 2023&lt;/td&gt;" "&lt;td&gt;6.77%&lt;/td&gt;"  
[3,] "&lt;td&gt;137.2571&lt;/td&gt;" "&lt;td&gt;Oct / 2023&lt;/td&gt;" "&lt;td&gt;1.59%&lt;/td&gt;"  
[4,] "&lt;td&gt;0.9466&lt;/td&gt;"   "&lt;td&gt;Oct / 2023&lt;/td&gt;" "&lt;td&gt;4.67%&lt;/td&gt;"  
[5,] "&lt;td&gt;828.1470&lt;/td&gt;" "&lt;td&gt;Oct / 2023&lt;/td&gt;" "&lt;td&gt;0.28%&lt;/td&gt;"  
     [,5]              
[1,] "&lt;td&gt;-13.07%&lt;/td&gt;"
[2,] "&lt;td&gt;-15.96%&lt;/td&gt;"
[3,] "&lt;td&gt;-2.22%&lt;/td&gt;" 
[4,] "&lt;td&gt;-6.90%&lt;/td&gt;" 
[5,] "&lt;td&gt;83.55%&lt;/td&gt;" </code></pre>
</div>
</div>
<p>Now construct a tibble from the above matrix and this will be our final product of the table from the url</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># final table</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>exchange_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">Country =</span> dollaEx_matrix_clean[, <span class="dv">1</span>],</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">LatestData =</span> dollaEx_matrix_clean[, <span class="dv">3</span>],</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">LatesValue =</span> dollaEx_matrix_clean[, <span class="dv">2</span>],</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">Change3months =</span> dollaEx_matrix_clean[ ,<span class="dv">4</span>],</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">Change12months =</span> dollaEx_matrix_clean[ ,<span class="dv">5</span>]</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(exchange_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  Country                     LatestData LatesValue Change3months Change12months
  &lt;chr&gt;                       &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;         &lt;chr&gt;         
1 "&lt;td&gt;&lt;a href='/Afghanistan… &lt;td&gt;Oct /… &lt;td&gt;75.47… &lt;td&gt;-13.35%&lt;… &lt;td&gt;-13.07%&lt;/…
2 "&lt;td&gt;&lt;a href='/Albania/Dol… &lt;td&gt;Oct /… &lt;td&gt;100.1… &lt;td&gt;6.77%&lt;/t… &lt;td&gt;-15.96%&lt;/…
3 "&lt;td&gt;&lt;a href='/Algeria/Dol… &lt;td&gt;Oct /… &lt;td&gt;137.2… &lt;td&gt;1.59%&lt;/t… &lt;td&gt;-2.22%&lt;/t…
4 "&lt;td&gt;&lt;a href='/Andorra/Dol… &lt;td&gt;Oct /… &lt;td&gt;0.946… &lt;td&gt;4.67%&lt;/t… &lt;td&gt;-6.90%&lt;/t…
5 "&lt;td&gt;&lt;a href='/Angola/Doll… &lt;td&gt;Oct /… &lt;td&gt;828.1… &lt;td&gt;0.28%&lt;/t… &lt;td&gt;83.55%&lt;/t…
6 "&lt;td&gt;&lt;a href='/Antigua-and… &lt;td&gt;Oct /… &lt;td&gt;2.702… &lt;td&gt;0.00%&lt;/t… &lt;td&gt;0.00%&lt;/td&gt;</code></pre>
</div>
</div>
<p>Further clean up process for the columns (They don’t contain usable date yet), so many html tags that needs to be removed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>exchange_data <span class="ot">&lt;-</span> exchange_data <span class="sc">%&gt;%</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Country =</span> <span class="fu">str_remove</span>(Country, <span class="at">pattern =</span> <span class="st">"/Dollar_exchange_rate/.*"</span>), <span class="co"># remove all characters after "/Dollar_exchange_rate/"</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Country =</span> <span class="fu">str_remove</span>(Country, <span class="at">pattern =</span> <span class="st">"&lt;td&gt;&lt;a href='/"</span>)            <span class="co"># remove the start tag for each value of country</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(exchange_data, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  Country     LatestData          LatesValue        Change3months Change12months
  &lt;chr&gt;       &lt;chr&gt;               &lt;chr&gt;             &lt;chr&gt;         &lt;chr&gt;         
1 Afghanistan &lt;td&gt;Oct / 2023&lt;/td&gt; &lt;td&gt;75.4778&lt;/td&gt;  &lt;td&gt;-13.35%&lt;… &lt;td&gt;-13.07%&lt;/…
2 Albania     &lt;td&gt;Oct / 2023&lt;/td&gt; &lt;td&gt;100.1403&lt;/td&gt; &lt;td&gt;6.77%&lt;/t… &lt;td&gt;-15.96%&lt;/…
3 Algeria     &lt;td&gt;Oct / 2023&lt;/td&gt; &lt;td&gt;137.2571&lt;/td&gt; &lt;td&gt;1.59%&lt;/t… &lt;td&gt;-2.22%&lt;/t…
4 Andorra     &lt;td&gt;Oct / 2023&lt;/td&gt; &lt;td&gt;0.9466&lt;/td&gt;   &lt;td&gt;4.67%&lt;/t… &lt;td&gt;-6.90%&lt;/t…
5 Angola      &lt;td&gt;Oct / 2023&lt;/td&gt; &lt;td&gt;828.1470&lt;/td&gt; &lt;td&gt;0.28%&lt;/t… &lt;td&gt;83.55%&lt;/t…</code></pre>
</div>
</div>
<p>The rest contain almost similar pattern, we are going to clean all them at a go. Basically remove the patterns/tags <code>&lt;td&gt;</code> and <code>&lt;/td&gt;</code> from our columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>exchange_data <span class="ot">&lt;-</span> exchange_data <span class="sc">%&gt;%</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">c</span>(LatestData<span class="sc">:</span>Change12months),</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">.fns =</span> <span class="sc">~</span> <span class="fu">str_remove_all</span>(., <span class="at">pattern =</span> <span class="st">"&lt;td&gt;|&lt;/td&gt;"</span>)    <span class="co"># remove the patterns "&lt;td&gt;|&lt;/td&gt;"</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>                  )) <span class="sc">%&gt;%</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(LatesValue, as.numeric),                              <span class="co"># convert to numeric column containing exchange rate</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>         </span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>         <span class="co"># On the date column; remove white space and replace "/" with "-"</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">LatestData =</span> <span class="fu">str_squish</span>(</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>           <span class="fu">str_replace_all</span>(</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">string =</span> LatestData,</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">pattern =</span> <span class="st">"/"</span>,</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">replacement =</span> <span class="st">"-"</span></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>         )) <span class="sc">%&gt;%</span> </span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># transform `LatestData` into a proper date column</span></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">LatestData =</span> <span class="fu">my</span>(LatestData),                       <span class="co"># proper date format</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">LatestData =</span> <span class="fu">format</span>(LatestData, <span class="st">"%Y-%m"</span>)           <span class="co"># YYYY-mm</span></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>exchange_data <span class="sc">%&gt;%</span> </span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>(<span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  Country    LatestData LatesValue Change3months Change12months
  &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt;         
1 Uruguay    2023-10          39.6 4.72%         -3.58%        
2 Uzbekistan 2023-10       12215.  5.52%         9.95%         
3 Vanuatu    2018-06         109.  -0.00%        -0.63%        
4 Vietnam    2023-10       24485.  3.46%         0.63%         
5 Yemen      2023-10        1239   0.00%         0.00%         
6 Zambia     2023-10          21.5 16.24%        35.05%        </code></pre>
</div>
</div>
<p><strong>NOTE</strong>: The downside of this manual approach is that it always depends on the website not changing structure, for instance if we had other countries added after Zambia, then our code above would not be able to extract that extra data sadly.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="cmaronga/codecraft.blog" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->



</body></html>